name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: 1. name.py 출력
      run: python name.py
      
    - name: 2. pip 업그레이드
      run: python -m pip install --upgrade pip
      
    - name: 3. 필요한 패키지 install
      run: pip install -r requirements.txt
      
    - name: 4. 파이썬 실행
      run: python test.py
